name: CI-CD-Pipeline-to-AWS-ElasticBeastalk
env:
  EB_PACKAGE_S3_BUCKET_NAME : "getip-flask-application"
  EB_APPLICATION_NAME       : "Getip"
  EB_ENVIRONMENT_NAME       : "Getip-env"
  DEPLOY_PACKAGE_NAME       : "getip_flask_app_${{ github.sha }}.zip"
  AWS_REGION_NAME           : "us-west-2"

on:
  push:
    branches:
      - master

jobs:
  ci_part:
    runs-on: ubuntu-latest

    steps:
    - name: git clone our repo
      uses: actions/checkout@v3

      
    - name: Create ZIP deployment package
      run : zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*
     
